---
- name: Change psql pg_hba.conf all peer authentication to {{ psql_local_trust_policy }}
  become: yes
  community.postgresql.postgresql_pg_hba:
    dest: "{{ psql_pg_hba_path }}"
    contype: "local"
    method: "{{ psql_local_trust_policy }}"
  notify:
    - Restart psql

- name: Change psql pg_hba.conf postgres peer authentication to {{ psql_local_trust_policy }}
  become: yes
  community.postgresql.postgresql_pg_hba:
    dest: "{{ psql_pg_hba_path }}"
    contype: "local"
    users: "postgres"
    method: "{{ psql_local_trust_policy }}"
  notify:
    - Restart psql

- name: Flush restart handler
  meta: flush_handlers
