---
- name: Add postgresql apt GPG key
  become: yes
  apt_key:
    url: "{{ psql_aptkey_url }}"
    state: present

- name: Add postgresql repo
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql

- name: Install postgresql
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 600
    name:
      - postgresql
    state: present

- name: Pip install psycopg2
  become: yes
  pip:
    name:
      - psycopg2-binary
