---
- name: Reconciliate hostname and inventory name
  become: yes
  lineinfile:
    dest: "{{ etc_hosts_path }}"
    regex: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ ansible_hostname }}"
    mode: "0644"

- name: Refresh ansible_facts
  setup:
