---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.15.0
    hooks:
      - id: ansible-lint
        always_run: true
        pass_filenames: false
        verbose: true
        entry: ansible-lint --force-color -p -v
