---
collections:
  - name: community.docker
    version: ">2.0.0,<3.0.0"
  - name: community.general
    version: ">=4.2.0,<5.0.0"

roles:
  - src: https://github.com/elliotweiser/ansible-osx-command-line-tools.git
    version: master
