---
- name: Setup Unifi cloud controller server
  hosts: unifi_cloud_controller
  gather_facts: yes

  roles:
  - role: timezone
  - role: motd
  - role: zsh
  - role: python
  - role: sshd
  - role: docker
  - role: docker_unifi
  - role: docker_nginx
