---
- name: Remove pve-enterprise repo
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise
    state: absent

- name: Add pve-no-subscription repo
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    filename: proxmox-no-subscription
    state: present
    mode: "0644"

- name: Update and upgrade apt packages
  apt:
    # upgrade: "yes"
    update_cache: yes
    # autoremove: yes
    cache_valid_time: 86400
