---
- name: Set virtualenvwrapper block in .bashrc
  blockinfile:
    path: "{{ virtualenvwrapper_shell_file }}"
    insertbefore: "EOF"
    marker: '# {mark} ANSIBLE MANAGED VENV'
    block: "{{ lookup('template', '.zshrc.j2') }}"
    mode: 0600
