---
- name: Install python3-pip
  become: true
  apt:
    name: python3-pip
    state: present

- name: Install virtualenvwrapper using pip
  pip:
    name: virtualenvwrapper

- name: Create virtualenv project directory
  action:
    module: file
    path: "{{ virtualenvwrapper_project }}"
    state: directory
    mode: 0755
