---
- name: Install python3-pip (Ubuntu/Debian)
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 600
    name: python3-pip
    state: present
  when: ansible_distribution == 'Ubuntu' or
        ansible_distribution == 'Debian'

- name: Install virtualenvwrapper using pip
  pip:
    name: virtualenvwrapper

- name: Create virtualenv project directory
  action:
    module: file
    path: "{{ virtualenvwrapper_project }}"
    state: directory
    mode: 0755
