---
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the server if required
  become: yes
  command: /sbin/shutdown -r now 'Rebooting to update system libs'
  args:
    removes: /var/run/reboot-required
  async: "{{ reboot_timeout }}"
  poll: 0
  when: reboot_required.stat.exists

- name: Wait for system to become reachable again
  wait_for_connection:
    delay: "{{ reboot_retry_time }}"
    timeout: "{{ reboot_timeout }}"
  when: reboot_required.stat.exists
