---
- name: Install zsh on ubuntu
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true

- name: Configure zsh
  include_tasks: configure.yml

- name: Configure .zshenv
  ansible.builtin.blockinfile:
    create: true
    path: "{{ zshenv_path }}"
    insertbefore: "EOF"
    marker: "# {mark} ANSIBLE MANAGED ENVIRONMENT"
    block: "{{ lookup('template', '.zshenv.debian.j2') }}"
    mode: 0600
