---
- ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Ubuntu" or
        ansible_distribution == "Debian"
- ansible.builtin.include_tasks: redhat.yml
  when: ansible_distribution == "CentOS" or
        ansible_distribution == "RedHat" or
        ansible_distribution == "Fedora"
