---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_2204
    image: ubuntu:22.04
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu_2204:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
