---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify that zsh package is installed
      ansible.builtin.apt:
        name: zsh
        state: present
      check_mode: true
      register: zsh_package

    - name: Verify that zsh is the default shell
      ansible.builtin.shell: 'grep "$(whoami)" /etc/passwd'
      register: zsh_shell
      failed_when: zsh_shell.stdout.find('/bin/zsh') == -1

    - name: Verify that zshrc file exists
      ansible.builtin.stat:
        path: $HOME/.zshrc
      register: zshrc_file

    - name: Verify that zshenv file exists
      ansible.builtin.stat:
        path: $HOME/.zshenv
      register: zshenv_file
