---
zsh_bin_path: "/usr/bin/zsh"
zshrc_path: '$HOME/.zshrc'
zshenv_path: '$HOME/.zshenv'
zsh_antigen_url: 'https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh'
zsh_antigen_dir: '/usr/share/zsh-antigen'
zsh_antigen_path: '/usr/share/zsh-antigen/antigen.zsh'
zsh_antigenrc_path: '$HOME/.antigenrc'
zsh_antigen_theme: 'robbyrussell'
zsh_p10k_path: '$HOME/.p10k.zsh'
