---
- name: Install oh-my-posh
  become: true
  get_url:
    url: "{{ omp_bin_src }}"
    dest: "{{ omp_bin_dest }}"
    mode: 0755

- name: Configure shell to use oh-my-posh
  blockinfile:
    create: true
    path: "{{ shellrc_path }}"
    insertbefore: "EOF"
    marker: '# {mark} ANSIBLE MANAGED OH-MY-POSH OPTIONS'
    block: "{{ lookup('template', 'rc.j2') }}"
    mode: 0600

- name: Create oh-my-posh themes directory
  file:
    path: "{{ omp_theme_dir }}"
    state: directory
    mode: 0755

- name: Install oh-my-posh themes
  get_url:
    url: "{{ omp_theme_src }}"
    dest: "{{ omp_theme_dir }}"
    remote_src: true
