---
- name: add linux.dell.com apt-key
  apt_key:
    keyserver: "{{ dell_linux_apt_keyserver }}"
    id: "{{ dell_linux_apt_key }}"

- name: add ubuntu.com apt-key
  apt_key:
    keyserver: "{{ ubuntu_keyserver }}"
    id: "{{ ubuntu_key }}"

- name: Add linux.dell.com source
  apt_repository:
    repo: "{{ item }}"
    filename: linux-dell
    state: present
    mode: "0644"
  loop:
  - "deb {{ dell_linux_omsa_repo }}/{{ dell_linux_distro }} {{ dell_linux_distro }} main"
  - "deb {{ dell_linux_ism_repo }}/{{ dell_linux_distro }} {{ dell_linux_distro }} main"

- name: "Add ubuntu {{ dell_linux_distro }} for dependencies"
  apt_repository:
    repo: "deb {{ ubuntu_repo }} {{ dell_linux_distro }} universe multiverse"
    filename: "ubuntu-{{ dell_linux_distro }}"
    state: present
    mode: "0644"

- name: "Set Debian package as priority"
  copy:
    src: ubuntuconf
    dest: /etc/apt/apt.conf.d/71ubuntuconf
    mode: "0644"

- name: Update apt packages
  apt:
    update_cache: yes
