---
- name: Add docker apt GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker

- name: Install docker-ce
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 600
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Install docker SDK pip module
  become: yes
  pip:
    name:
      - docker>=5.0.0,<6.0.0
      - docker-compose>=1.7.0,<2.0.0
