---
- name: Install vim
  become: yes
  apt:
    name: vim
    state: present

- name: Add vimrc settings
  lineinfile:
    path: "{{ vimrc_path }}"
    line: "{{ item }}"
    insertbefore: "EOF"
    state: present
    create: yes
    mode: "0600"
  with_items:
    - set t_Co=256
    - set laststatus=2
    - set showtabline=2
    - set noshowmode
    - set dir=/tmp
