---
- name: Install maas
  become: yes
  community.general.snap:
    name: maas
    channel: "{{ maas_snap_channel }}"

- name: Create maas psql user {{ maas_psql_username }}
  become: yes
  community.postgresql.postgresql_user:
    name: "{{ maas_psql_username }}"
    password: "{{ maas_psql_password }}"

- name: Create maas psql db {{ maas_psql_db }}
  become: yes
  community.postgresql.postgresql_db:
    name: "{{ maas_psql_db }}"
    owner: "{{ maas_psql_username }}"
