---
- name: Set SSH authorized_keys
  authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ ssh_key }}"
    comment: "{{ ssh_key_comment }}"

- name: Implement sshd_config
  become: yes
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart sshd
