---
- name: Install font-manager
  become: yes
  apt:
    name: font-manager
    state: present

- name: Ensure fonts directory is present
  file:
    path: "{{ fonts_dir_path }}"
    state: directory
    recurse: yes
    mode: 0755

- name: Install fonts
  get_url:
    url: "{{ item.url }}"
    dest:  "{{ fonts_dir_path }}/{{ item.name }}"
  with_items: "{{ fonts }}"
